### ISSUE TITLE
Разработка микросервиса Worker

### ISSUE THREAD

**Issue by IWillBurn** [5krotov/task-resolver#4]
### Обзор:
Worker — Go-микросервис, выполняющий нагрузку. Worker реализует функциональность выполнения задач и разворот data-flow приложения.

### Требования:
- настройка микросервиса происходит через конфиг
- микросервис читает задачи из kafka-топика (пока их число меньше queue_size)
- микросервис выполняет задачи (не более threads одновременно)
- микросервис пишет в kafka-топик статус задачи

*удаление задачи из kafka происходит только после её полного выполнения*

#### Конфиг
```yaml
kafka:
    addr: [string]
    group: [string]
    task_topic: [string]
    status_topic: [string]

worker:
    queue_size:  [int]
    threads:  [int]
...
```
#### Задача
```json
{
    "id": { "type": "int64" }
    "difficulty": { "type": "int" }
}
```
#### Статус
```json
{
    "id": { "type": "int64" }
    "status": { "type": "int" }
}
```
#### Статусы задач
```enum
CREATED: 0
PENDING: 1
IN_PROGRESS: 2
DONE: 3
```
