### ISSUE TITLE
Разработка Agent-Service

### ISSUE THREAD

**Issue by IWillBurn** [5krotov/task-resolver#7]
### Обзор:
Agent-Service — Go-микросервис, контр-агент Worker-Service, обрабатывает изменения статуса задач.
 
### Требования:
- настройка микросервиса происходит через конфиг
- микросервис корректно обрабатывает REST-запросы
- микросервис возвращает корректные HTTP-коды
- микросервис пишет новые задачи в kafka-топик
- микросервис читает запросы на обновление статусов из kafka-топика
- микросервис использует Data-Provider-Service для обновления статуса задач
- микросервис корректно обрабатывает ошибки
- микросервис пишет логи

#### Конфиг
```yaml
kafka:
    addr: [string]
    group: [string]
    task_topic: [string]
    status_topic: [string]

data-provider:
     addr: [string]

agent:
    http:
        port: [string]
...
```
#### Задача
```json
{
    "id": { "type": "int64" }
    "difficulty": { "type": "int" }
}
```
#### Изменение статуса
```json
{
    "id": { "type": "int64" }
    "status": { "type": "int" }
    "timestamp": { "type": "timestamp" }
}
```
### Запросы
[POST] /task/
in:
```json
{
    "id": { "type": "int64" }
    "difficulty": { "type": "int" }
}
```
